# Driver configuration
CONFIG_GPIO=y

# Enable RTT console logs
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n

# Logging backend configuration
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
